morus_fas_homepage:
    path:     /
    defaults: { _controller: MorusFasBundle:Default:index }

morus_fas_statement:
    resource: "@MorusFasBundle/Resources/config/routing/statement.yml"
    prefix:   /Fas/Statement
    
morus_fas_accountsReceivable:
    resource: "@MorusFasBundle/Resources/config/routing/ar.yml"
    prefix:   /Fas/AccountsReceivable
    
morus_fas_contacts:
    resource: "@MorusFasBundle/Resources/config/routing/contacts.yml"
    prefix:   /Fas/Contacts
    
morus_fas_inventory:
    resource: "@MorusFasBundle/Resources/config/routing/inventory.yml"
    prefix:   /Fas/Inventory
    
morus_fas_export:
    resource: "@MorusFasBundle/Resources/config/routing/export.yml"
    prefix:   /Fas/Export