services:
    # Form Flow
    morus_fas.form.flow.statement.import:
        class: Morus\FasBundle\Form\ImportFlow
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        parent: craue.form.flow
        scope: request
        
    morus_fas.form.flow.invoice.export:
        class: Morus\FasBundle\Form\ExportFlow
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        parent: craue.form.flow
        scope: request
        
    morus_fas.form.flow.invoice.export.pl:
        class: Morus\FasBundle\Classes\PL
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    
    # Form Type
    morus_fas.form.type.statement:
        class: Morus\FasBundle\Form\Type\StatementType
        tags:
            - { name: form.type, alias: fas_statement }
          
    morus_fas.form.type.statementList:
        class: Morus\FasBundle\Form\Type\StatementListType
        tags:
            - { name: form.type, alias: fas_statement_list }
    
    morus_fas.form.type.product:
        class: Morus\FasBundle\Form\Type\ProductType
        tags:
            - { name: form.type, alias: fas_product }
    
    morus_fas.form.type.unit:
        class: Morus\FasBundle\Form\Type\UnitType
        tags:
            - { name: form.type, alias: fas_unit }
    
    morus_fas.form.type.unit_product:
        class: Morus\FasBundle\Form\Type\UnitProductType
        tags:
            - { name: form.type, alias: fas_unit_product }
            
    morus_fas.form.type.vehicle:
        class: Morus\FasBundle\Form\Type\VehicleType
        tags:
            - { name: form.type, alias: fas_vehicle }
            
    morus_fas.form.type.transaction:
        class: Morus\FasBundle\Form\Type\TransactionType
        tags:
            - { name: form.type, alias: fas_transaction }
    
    morus_fas.form.type.ar.list:
        class: Morus\FasBundle\Form\Type\ArListType
        tags:
            - { name: form.type, alias: fas_ar_list }
            
    morus_fas.form.type.ar:
        class: Morus\FasBundle\Form\Type\ArType
        tags:
            - { name: form.type, alias: fas_ar }
    
    morus_fas.form.type.invoice:
        class: Morus\FasBundle\Form\Type\InvoiceType
        tags:
            - { name: form.type, alias: fas_invoice }
       
    morus_fas.form.type.invoices:
        class: Morus\FasBundle\Form\Type\InvoicesType
        tags:
            - { name: form.type, alias: fas_invoices }        
    
    morus_fas.form.type.contact:
        class: Morus\FasBundle\Form\Type\ContactType
        tags:
            - { name: form.type, alias: fas_contact } 
            
    morus_fas.form.type.location:
        class: Morus\FasBundle\Form\Type\LocationType
        tags:
            - { name: form.type, alias: fas_location } 
            
    morus_fas.form.type.person:
        class: Morus\FasBundle\Form\Type\PersonType
        tags:
            - { name: form.type, alias: fas_person }
    
    morus_fas.form.type.product:
        class: Morus\FasBundle\Form\Type\ProductType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fas_product }

    morus_fas.form.type.product_list:
        class: Morus\FasBundle\Form\Type\ProductListType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: fas_product_list }
            
    # Utility Classes
    morus_fas.classes.importlog:
        class: Morus\FasBundle\Classes\ImportLog
        arguments: ["@translator"]
