morus_fas_statement:
    path:     /
    defaults: { _controller: "MorusFasBundle:Statement:index" }

morus_fas_statement_import:
    path:     /import
    defaults: { _controller: "MorusFasBundle:Statement:import" }

morus_fas_statement_export:
    path:     /export
    defaults: { _controller: "MorusFasBundle:Statement:export" }
    
morus_fas_statement_export_unit_vehicle_list:
    path:     /unit_vehicle_list
    defaults: { _controller: "MorusFasBundle:Statement:unitVehicleList" }
 
morus_fas_statement_export_parts_list:
    path:     /parts_list
    defaults: { _controller: "MorusFasBundle:Statement:partsList" }
    
morus_fas_statement_export_create_product_ajax:
    path:     /product/new
    defaults: { _controller: "MorusFasBundle:Statement:createProductAjax" }


    
morus_fas_statement_customer_list:
    path:     /customer/list
    defaults: { _controller: "MorusFasBundle:Statement:customerList" }  

morus_fas_statement_customer_update:
    path:     /customer/create
    defaults: { _controller: "MorusFasBundle:Statement:customerUpdate" }

morus_fas_statement_customer_dialog:
    path:     /customer/dialog
    defaults: { _controller: "MorusFasBundle:Statement:customerDialog" }


morus_fas_statement_delete:
    path:     /delete
    defaults: { _controller: "MorusFasBundle:Statement:delete" }
